### ISSUE TITLE
live_bounds parameter seems incorrect and cannot be correctly bound

### ISSUE THREAD

**Issue by graydianzhang** [lizhe00/PoseVocab#5]
Great job. I tried the CMU dataset and did SMPL fitting well, but during training, I couldn't do it. After checking, I found that live_ Bounds cannot be drawn correctly. Can you tell me what this is related to? Camera calibration?
my error：
 File "/project-ssd/PoseVocab/dataset/dataset_mv_rgb_slrf.py", line 257, in getitem
    nerf_random = nerf_util.sample_randomly_for_nerf_rendering(color_img, mask_img, depth_img, self.extr_mats[view_idx], self.intr_mats[view_idx], live_bounds, unsample_region_mask = boundary_mask_img, **ray_sampling['random'])
  File "/project-ssd/PoseVocab/utils/nerf_util.py", line 293, in sample_randomly_for_nerf_rendering
    sampled_inside_uv = inside_uv[np.random.choice(inside_uv.shape[0], inside_sample_num, replace = False)]
  File "mtrand.pyx", line 909, in numpy.random.mtrand.RandomState.choice
ValueError: a must be greater than 0 unless no samples are taken

**Comment by graydianzhang** [comment]
Alternatively, you can tell me how to process your own data in THUman4 format

**Comment by lizhe00** [comment]
Hi, maybe your SMPL parameter format is not the same as ours, you can visualize the SMPL and project it to the image to visualize the SMPL fitting.

**Comment by graydianzhang** [comment]
Yes thank you very much , I checked that my smpl data does have an error in relation to global_orient , transl seems to have an error, the pose attribute should be correct, I tried [mvsmplfitting](https://github.com/boycehbz/MvSMPLfitting) and it seems that I can't get the correct smpl data either, can you tell me to get the correct smpl_params.npz through that repo, thank you very much!!
